### ISSUE TITLE
Cube #485 broken

### ISSUE THREAD

**Issue by Arrhythmiagamer23** [user95401/InDeCreaseIcons#1]
So, i encountered a bug on my project i'm making called Geometry dash breeze refreshed, can you fix it?
![20240219170523_1](https://github.com/user95401/InDeCreaseIcons/assets/158773839/1d2760e3-2cf3-49f3-85cb-65647df56556)

**Comment by lil2kki** [comment]
where locating ur icons textures?

**Comment by Arrhythmiagamer23** [comment]
in the resources/icons folder but #485 dosen't work on my system.

**Comment by lil2kki** [comment]
give me new resources that u add, i try solove smth

**Comment by Arrhythmiagamer23** [comment]
https://drive.google.com/drive/folders/14uYFRwDLOJkfWuMJjz1mDs2mSeVItd2p?usp=sharing
here it is!

**Comment by Arrhythmiagamer23** [comment]
it's a baby yoshi that can be unlocked after beating pixel pig in normal mode.

**Comment by lil2kki** [comment]
hmm idk why mod dont load it

**Comment by lil2kki** [comment]
its better if u merge all new icons into _IconsSheet.plist
because its 100% will be loaded unlike shitty preload system

**Comment by Arrhythmiagamer23** [comment]
oh, right!

**Comment by Arrhythmiagamer23** [comment]
nope, still didn't work!

**Comment by Arrhythmiagamer23** [comment]
can you fix it?

**Comment by lil2kki** [comment]
where u put _IconsSheet.plist?

**Comment by Arrhythmiagamer23** [comment]
in the resources folder

**Comment by Arrhythmiagamer23** [comment]
https://drive.google.com/drive/folders/1Es6s16gp_1FVFM7SxG4xui66KUkL8oGH?usp=sharing

**Comment by lil2kki** [comment]
why u send GJ_GameSheetIcons-hd.plist
u need create exactly `_IconsSheet.plist`

**Comment by Arrhythmiagamer23** [comment]
ok.

**Comment by Arrhythmiagamer23** [comment]
well, i like using HD files.
