### ISSUE TITLE
cant find IconsSheet.plist

### ISSUE THREAD

**Issue by thatoneguy2763** [user95401/InDeCreaseIcons#11]
can you tell where "IconsSheet.plist" is? im having trouble finding it

**Comment by lil2kki** [comment]
u should create it
this is not official sheet name

and it must be called `_IconsSheet.plist`

**Comment by thatoneguy2763** [comment]
ok but what folder do i put it in

**Comment by lil2kki** [comment]
any folder  where game founds resources
for example:
- ./
- ./Resources/
- packs u loaded

**Comment by thatoneguy2763** [comment]
kk

**Comment by thatoneguy2763** [comment]
> kk
