### ISSUE TITLE
Add option to unlock new icons only & auto-detect

### ISSUE THREAD

**Issue by Asterveila** [user95401/InDeCreaseIcons#3]
Hi, mod's pretty cool but i'd like to suggest adding the feature from 2.1's more icons mod where it can automatically detect the amount of icons in your texture pack instead of having to set them manually, as well as maybe an option to unlock only the new icons you've added so icon hack isn't necessary unlocking every other icon as well

**Comment by lil2kki** [comment]
no auto-detect soon
but unlock news i can

**Comment by Asterveila** [comment]
sick! i don't mind no auto detect honestly, i can live without it

**Comment by lil2kki** [comment]
anyways unlock news in beta5.
https://github.com/user95401/InDeCreaseIcons/blob/main/src/main.cpp#L447

**Comment by Asterveila** [comment]
huh wasn't this already completed is this getting discontinued or ported to 2.206?

**Comment by lil2kki** [comment]
rewrite

**Comment by Asterveila** [comment]
oh cool gl
please make the robots and spiders work 😭🙏
