### ISSUE TITLE
Icon amounts not saving

### ISSUE THREAD

**Issue by DeepResonanceX** [user95401/InDeCreaseIcons#4]
Basically what the title says, icon amounts aren't saving between game sessions, every time the game is restarted the amounts are reset to normal, changing them on the config file instead of the in-game config menu doesn't seem to do anything either.
It'd be better if the mod detected the amounts automatically tbh

**Comment by lil2kki** [comment]
okkk 
fixing

**Comment by lil2kki** [comment]
fixed

**Comment by DeepResonanceX** [comment]
seems to be working fine now so ty, however, is it not possible at all to add new robots or spiders? i've tried adding a few but it just reuses the last robot/spider sprite instead of the new one
if so, is it planned to add support for them?

**Comment by lil2kki** [comment]
idk how to fix that)

**Comment by lil2kki** [comment]
about that stuff is better to ask zGuschin

**Comment by lil2kki** [comment]
@rnmnx in discord
