### ISSUE TITLE
Robot #69 not reading high detail texture

### ISSUE THREAD

**Issue by splidgesplodge** [user95401/InDeCreaseIcons#5]
I have added a robot as robot_69-uhd.(png/plist) and it will not use that texture. It instead uses robot 68s texture.

![image_2024-04-09_144528270](https://github.com/user95401/InDeCreaseIcons/assets/166522230/086ebd15-c10b-4662-a381-13ac804e7774)

**Comment by lil2kki** [comment]
should not even
idk how to fix
