### ISSUE TITLE
Icons bugged?? 

### ISSUE THREAD

**Issue by OhYeahMrKrabs87** [user95401/InDeCreaseIcons#6]
All added icons for me are broken. Please fix soon!! 
![IMG_20240411_233306808_HDR](https://github.com/user95401/InDeCreaseIcons/assets/166782100/1441e182-c570-43b2-b32f-ae09803d1860)

**Comment by lil2kki** [comment]
u made it wrong i guess
how u add resources?

**Comment by OhYeahMrKrabs87** [comment]
> u made it wrong i guess how u add resources?

I added it to the mod files. Not like in the game. But in the whole file for the mod with "Settings.json"

**Comment by lil2kki** [comment]
u should put resource where game is looking for it
like `./` or `./Resources/`

**Comment by OhYeahMrKrabs87** [comment]
> u should put resource where game is looking for it
> like `./` or `./Resources/`

Oh, ok

**Comment by OhYeahMrKrabs87** [comment]
> u should put resource where game is looking for it
> like `./` or `./Resources/`

It's working now, thank you
