### ISSUE TITLE
two things

### ISSUE THREAD

**Issue by coltenisthebest** [user95401/InDeCreaseIcons#7]
1: when i go to the robot tab the game crashes
2: where do i put my custom icons?

**Comment by coltenisthebest** [comment]
(also the spider tab crashes)

**Comment by lil2kki** [comment]
1:
![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/62e48099-218a-4ecb-8c84-e106898fcf66)
![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/48127966-5d12-4ebc-adc4-8866f362bc8f)
2: 
![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/f43cab46-8a76-42b5-84bd-23cd9567668c)
## or 
![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/4c738345-6db6-4df2-aa12-3719a318e7b1)

**Comment by lil2kki** [comment]
_IconsSheet.plist example
https://github.com/user95401/InDeCreaseIcons/releases/download/beta2/_IconsSheet.plist
https://github.com/user95401/InDeCreaseIcons/releases/download/beta2/_IconsSheet.png

**Comment by coltenisthebest** [comment]
> 1: ![image](https://private-user-images.githubusercontent.com/90561697/322197660-62e48099-218a-4ecb-8c84-e106898fcf66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjIzODAsIm5iZiI6MTcxMzAyMjA4MCwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc2NjAtNjJlNDgwOTktMjE4YS00ZWNiLThjODQtZTEwNjg5OGZjZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzE2ODNhNTg4YWJjZTQ0Njc1ZTBmOTFhODg3MjdiMzUwY2Y3N2QzODAyYjlkMTRhZTY5NTI1ZTcxZDI5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PAQTbNHuW39vba6xJzrl_6c1c-di8q0Xo2DcKXEBTj0) ![image](https://private-user-images.githubusercontent.com/90561697/322197699-48127966-5d12-4ebc-adc4-8866f362bc8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjIzODAsIm5iZiI6MTcxMzAyMjA4MCwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc2OTktNDgxMjc5NjYtNWQxMi00ZWJjLWFkYzQtODg2NmYzNjJiYzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNDNlYWVkODZjM2ZlMWY0ZjY1NjNlZTA2ZTZhYmYzMWE5YzFmZjcyYTk3NTY5MDcxOTVjNTk2ZjY0NzBjZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fln23-5kgzC0lw78qZmCQD2mx2bP2mPkJmRnQcBTmyw) 2: ![image](https://private-user-images.githubusercontent.com/90561697/322197716-f43cab46-8a76-42b5-84bd-23cd9567668c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjIzODAsIm5iZiI6MTcxMzAyMjA4MCwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc3MTYtZjQzY2FiNDYtOGE3Ni00MmI1LTg0YmQtMjNjZDk1Njc2NjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZTk5NGUxZjE1Y2VmYTdkMTEyMDU5MmZiMDcxNTcwYzM1YWNiNDYyNjYwYzU3ZDEyNGU3Zjk3ZWZhNjA0ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DBhdcwU5879kp3wp_6WjcbtoHd-h634quB0X7A2KzG0)
> 
> ## or
> ![image](https://private-user-images.githubusercontent.com/90561697/322197765-4c738345-6db6-4df2-aa12-3719a318e7b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjIzODAsIm5iZiI6MTcxMzAyMjA4MCwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc3NjUtNGM3MzgzNDUtNmRiNi00ZGYyLWFhMTItMzcxOWEzMThlN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE1MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMWExYzkyMGZlNWU2NDkzOTY4ZDRkNjlkOTVlYzkyNDVmZDkyYjQxNzM1NDllYzdhZWRmODYxMjhhMjg3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DlTU4gCngUoHivIDu_4QMLG3qFIvxFmRfulQkL2_w0Y)

how do  ifix that

**Comment by coltenisthebest** [comment]
> _IconsSheet.plist example https://github.com/user95401/InDeCreaseIcons/releases/download/beta2/_IconsSheet.plist https://github.com/user95401/InDeCreaseIcons/releases/download/beta2/_IconsSheet.png

How do i fix the crash?

**Comment by lil2kki** [comment]
what crash

**Comment by coltenisthebest** [comment]
> what crash

when i go to the robot / spider tab

**Comment by coltenisthebest** [comment]
(when i add more robots / spiders)

**Comment by lil2kki** [comment]
> 1:
> ![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/62e48099-218a-4ecb-8c84-e106898fcf66)
> ![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/48127966-5d12-4ebc-adc4-8866f362bc8f)
> 2: 
> ![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/f43cab46-8a76-42b5-84bd-23cd9567668c)
> ## or 
> ![image](https://github.com/user95401/InDeCreaseIcons/assets/90561697/4c738345-6db6-4df2-aa12-3719a318e7b1)
>

**Comment by coltenisthebest** [comment]
i dont get it lol

> > 1:
> > ![image](https://private-user-images.githubusercontent.com/90561697/322197660-62e48099-218a-4ecb-8c84-e106898fcf66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjQ5OTIsIm5iZiI6MTcxMzAyNDY5MiwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc2NjAtNjJlNDgwOTktMjE4YS00ZWNiLThjODQtZTEwNjg5OGZjZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE2MTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYzM4MGY2NTYwMWI0YTAwMTc4ZTNhMTUxY2NkODI2OTAzZGQ5ODUyMzYxZjg1NmE4MDU0ZGVlNjI0MmIyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dq-QULjEa-JJzA8U3cuFcJCJMeotsCcmcoJwXjQ55qM)
> > ![image](https://private-user-images.githubusercontent.com/90561697/322197699-48127966-5d12-4ebc-adc4-8866f362bc8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjQ5OTIsIm5iZiI6MTcxMzAyNDY5MiwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc2OTktNDgxMjc5NjYtNWQxMi00ZWJjLWFkYzQtODg2NmYzNjJiYzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE2MTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4M2VkYjUxMjE4ZmY0MzA3NDg1MjY0NmUyNzIzZGM0ZDM4ODFjNDg5Y2YxOWY0ODQxZjhjOTVmYTNiOWI2MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zsmiktHKSAXsbIZFzjmw7JqUrXPtxGSzafjNPg7RNeI)
> > 2:
> > ![image](https://private-user-images.githubusercontent.com/90561697/322197716-f43cab46-8a76-42b5-84bd-23cd9567668c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjQ5OTIsIm5iZiI6MTcxMzAyNDY5MiwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc3MTYtZjQzY2FiNDYtOGE3Ni00MmI1LTg0YmQtMjNjZDk1Njc2NjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE2MTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYTM3ZTUwZDAyMjFjY2NkZGJmMmIxMWQyYzNkNDNhNTk4OTRjNmM3MmVjNmVmNGM4NTFkM2QxODU1M2VmYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NM3RbBeb0NKckI6sCKe7sbrYSoKGc5fcaDoitbUOdCM)
> > ## or
> > ![image](https://private-user-images.githubusercontent.com/90561697/322197765-4c738345-6db6-4df2-aa12-3719a318e7b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjQ5OTIsIm5iZiI6MTcxMzAyNDY5MiwicGF0aCI6Ii85MDU2MTY5Ny8zMjIxOTc3NjUtNGM3MzgzNDUtNmRiNi00ZGYyLWFhMTItMzcxOWEzMThlN2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE2MTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNWU5OGU3NTc1MGEyNDZkYzEyZWExZWVhMjFiN2Y0YjFhYTBjYzkzMTRlNjBiNzFlNzVkY2NkMDFlOGYyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPWJ-B_aj-tDjmgWqH6LPYjfEPlbZeUEGhAReoqC_q0)

**Comment by lil2kki** [comment]
its known bug
game cant load new resource or smth
fork mod and found solutions to fix that
i welcome contributing

**Comment by coltenisthebest** [comment]
> its known bug game cant load new resource or smth fork mod and found solutions to fix that i welcome contributing

what is fork mod?
