### ISSUE TITLE
robot & spider sprites not loading correctly

### ISSUE THREAD

**Issue by RazorLeaf16** [user95401/InDeCreaseIcons#8]
I'm using a texture pack that has exactly 109 robots and 79 spiders and when I checked the icons they only loaded the last icon's sprites. (both being robot 68 and spider 69)
![20240414173821_1](https://github.com/user95401/InDeCreaseIcons/assets/142274070/46e01540-8b87-43ad-b057-b7f97ca44263)
![20240414173823_1](https://github.com/user95401/InDeCreaseIcons/assets/142274070/692091fd-3288-4640-9b9e-6f30320ba855)

**Comment by RazorLeaf16** [comment]
*robot 68

**Comment by lil2kki** [comment]
https://github.com/user95401/InDeCreaseIcons/issues/7

**Comment by RazorLeaf16** [comment]
> #7

This is unrelated to my question; everything works fine cube to wave, but specifically, the robot and spider are the problem.

**Comment by lil2kki** [comment]
robots and spiders is unfinished.
in setting infos i wrote that game cant load new resources

**Comment by lil2kki** [comment]
https://github.com/user95401/InDeCreaseIcons/blob/main/mod.json#L67
